In [ ]:
import pandas  as pd 
 
df = pd.read_csv(r"Dataset\retail_store_inventory.csv")
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [ ]:
df[df["Category"] == "Groceries"]

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
5,2022-01-01,S001,P0006,Groceries,South,138,128,102,139.82,76.83,10,Sunny,1,79.35,Winter
20,2022-01-01,S002,P0001,Groceries,South,343,104,144,112.55,32.80,20,Sunny,1,30.78,Spring
26,2022-01-01,S002,P0007,Groceries,West,460,393,70,401.48,91.13,5,Sunny,0,93.33,Summer
30,2022-01-01,S002,P0011,Groceries,West,67,13,33,7.44,34.62,0,Snowy,1,33.98,Autumn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73070,2024-01-01,S004,P0011,Groceries,East,155,107,47,123.65,88.17,20,Snowy,1,90.26,Autumn
73081,2024-01-01,S005,P0002,Groceries,North,253,97,80,104.84,34.96,0,Cloudy,1,34.89,Summer
73086,2024-01-01,S005,P0007,Groceries,South,59,4,34,3.95,62.12,10,Rainy,1,66.85,Autumn
73090,2024-01-01,S005,P0011,Groceries,North,156,121,156,137.12,86.09,0,Snowy,1,87.83,Summer
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [3]:
df["Date"][df["Category"] == "Groceries"]

0        2022-01-01
5        2022-01-01
20       2022-01-01
26       2022-01-01
30       2022-01-01
            ...
73070    2024-01-01
73081    2024-01-01
73086    2024-01-01
73090    2024-01-01
73099    2024-01-01
Name: Date, Length: 14611, dtype: object

In [4]:
df["Date"][df["Category"] == "Groceries"].value_counts()

Date
2023-05-05    35
2023-05-17    32
2022-09-26    31
2022-11-02    31
2022-01-14    30
              ..
2023-07-24    11
2022-08-22    11
2023-08-16    10
2022-12-05    10
2023-02-12    10
Name: count, Length: 731, dtype: int64